### ISSUE TITLE
Default style json not found

### ISSUE THREAD

**Issue by junderwood36** [roblabs/xyz-raster-sources#3]
Hi Roblabs, Loving your work,
I noticed that on your codepen here   https://codepen.io/roblabs/pen/JjXXMLz
the default style.json file is not loading. It's 404 not found at the URL specified

https://raw.githubusercontent.com/roblabs/xyz-raster-sources/master/style.json

**Comment by roblabs** [comment]
Thanks for the feedback, @junderwood36 .  Yes, I did some refactoring of the style paths.  [CodePen](https://codepen.io/roblabs/pen/JjXXMLz) is now fixed with a single style that should work:  https://roblabs.com/xyz-raster-sources/styles/openstreetmap.json

---

All the styles are listed in this repo folder

* https://github.com/roblabs/xyz-raster-sources/tree/master/styles
